### ISSUE TITLE
Linux compiling instruction & binary package

### ISSUE THREAD

**Issue by ghost** [MeteorStudioASU/lcc#4]
### Compiling on Linux

Add instruction for Linux
 
### Provide AppImage (portable binary package) for Linux

Please, setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

- AppImage Docs - https://docs.appimage.org/

0. [ ] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2. https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any AppImage packaging questions & support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by hartwork** [comment]
What worked for me:
```bash
mkdir build
cd build
cmake ..
make VERBOSE=1
echo | ./lcc  # to prove executability, lcc lacks --help
```

**Comment by tsst-tsst** [comment]
Just for the sake of completeness, "make install" and "make uninstall" will also work. You can set the install path using the CMAKE_INSTALL_PREFIX variable.

It is also possible to use ninja instead of make like so: 

```
  mkdir build
  cd build
  cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr/local ..
  ninja
  ninja install   # optional: install the binary to /usr/local/bin
  ninja uninstall # optional: remove the binary from /usr/local/bin

```

In case you want to take a look at all the available variables, you may print all the options and default/cached values with:

```
cmake -LA | awk '{if(f)print} /-- Cache values/{f=1}' | less
```
