### ISSUE TITLE
Differences to bs2b?

### ISSUE THREAD

**Issue by hartwork** [MeteorStudioASU/lcc#6]
Hi!

Thanks for sharing this as software libre. For people who know [bs2b](http://bs2b.sourceforge.net/) it would be cool to understand how different or similar LCC is. Would be great to have in the readme.

Thanks and best, Sebastian

**Comment by mattlane66** [comment]
bs2b sounds completely different than LCC. Please see our white papers to learn more. bs2b sounds like a headphone product.

**Comment by hartwork** [comment]
I don't understand the language that the papers use. I guess I misread "your left ear hears the left channel of audio, and your right ear hears the right channel of audio" to the opposite which is why it sounded like bs2b to me: It mixes a bit of the right back into the left channel and vice versa. Alright, I'll close the ticket.
